package director

import (
	"archive/zip"
	"encoding/csv"
	"fmt"
	"io"
	"strings"

	"github.com/go-pdf/fpdf"
)

// reportMeta is the lawful-query header printed on every exported report.
type reportMeta struct {
	CaseRef     string
	GeneratedBy string
	GeneratedAt string
	QueryIP     string
	QueryPort   int
	QueryProto  string
	From        string
	To          string
	Count       int
	Truncated   bool
}

var reportCols = []string{"timestamp", "device", "private_nat", "public_nat", "protocol", "destination", "type"}

func rowCells(r natRecord) []string {
	return []string{
		r.Time, r.Sub, fmt.Sprintf("%s:%d", r.PrivIP, r.PrivPort),
		fmt.Sprintf("%s:%d", r.PubIP, r.PubPort), r.Proto, r.Dest, r.Action,
	}
}

func metaLines(m reportMeta) [][2]string {
	port := "any"
	if m.QueryPort > 0 {
		port = fmt.Sprintf("%d", m.QueryPort)
	}
	proto := m.QueryProto
	if proto == "" || proto == "Any" {
		proto = "any"
	}
	recs := fmt.Sprintf("%d", m.Count)
	if m.Truncated {
		recs += " (truncated — narrow the time window or port)"
	}
	return [][2]string{
		{"Audit reason", orDash(m.CaseRef)},
		{"Public IP", m.QueryIP}, {"Public port", port}, {"Protocol", proto},
		{"Time window", m.From + " — " + m.To},
		{"Records", recs},
		{"Generated", m.GeneratedAt + " by " + m.GeneratedBy},
	}
}

func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "—"
	}
	return s
}

// deFormula neutralizes spreadsheet formula injection: a cell whose first char
// is = + - @ (or tab/CR) is executed as a formula by Excel/Sheets, so prefix it
// with a single quote. Applied to CSV/XLSX exports (not PDF).
func deFormula(s string) string {
	if s != "" && strings.ContainsRune("=+-@\t\r", rune(s[0])) {
		return "'" + s
	}
	return s
}

func safeCells(in []string) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = deFormula(v)
	}
	return out
}

// --- CSV ---

func writeCSV(w io.Writer, m reportMeta, rows []natRecord) error {
	cw := csv.NewWriter(w)
	_ = cw.Write([]string{"Flow Log Report"})
	for _, kv := range metaLines(m) {
		_ = cw.Write([]string{kv[0], deFormula(kv[1])})
	}
	_ = cw.Write(nil)
	_ = cw.Write(reportCols)
	for _, r := range rows {
		_ = cw.Write(safeCells(rowCells(r)))
	}
	cw.Flush()
	return cw.Error()
}

// --- PDF (landscape A4) ---

func writePDF(w io.Writer, m reportMeta, rows []natRecord) error {
	pdf := fpdf.New("L", "mm", "A4", "")
	pdf.SetMargins(8, 10, 8)
	pdf.SetAutoPageBreak(true, 12)
	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 15)
	pdf.CellFormat(0, 8, "Flow Log Report", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	for _, kv := range metaLines(m) {
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(40, 5, kv[0], "", 0, "L", false, 0, "")
		pdf.SetTextColor(20, 20, 20)
		pdf.CellFormat(0, 5, kv[1], "", 1, "L", false, 0, "")
	}
	pdf.Ln(2)

	widths := []float64{34, 26, 50, 50, 18, 60, 24}
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetFillColor(0, 119, 182)
	pdf.SetTextColor(255, 255, 255)
	heads := []string{"Timestamp", "Device", "Private (NAT)", "Public (NAT)", "Proto", "Destination", "Type"}
	for i, h := range heads {
		pdf.CellFormat(widths[i], 6, h, "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetFont("Helvetica", "", 7.5)
	pdf.SetTextColor(30, 30, 30)
	fill := false
	for _, r := range rows {
		if fill {
			pdf.SetFillColor(245, 248, 251)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		for i, c := range rowCells(r) {
			pdf.CellFormat(widths[i], 5, trunc(c, 46), "LR", 0, "L", true, 0, "")
		}
		pdf.Ln(-1)
		fill = !fill
	}
	pdf.SetFont("Helvetica", "I", 7)
	pdf.SetTextColor(150, 150, 150)
	pdf.Ln(2)
	pdf.CellFormat(0, 5, "Generated by YesLogs Director · access is audited", "", 1, "C", false, 0, "")
	return pdf.Output(w)
}

func trunc(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}

// --- XLSX (hand-rolled minimal OOXML, inline strings, no deps) ---

func writeXLSX(w io.Writer, m reportMeta, rows []natRecord) error {
	zw := zip.NewWriter(w)
	add := func(name, content string) error {
		f, err := zw.Create(name)
		if err != nil {
			return err
		}
		_, err = io.WriteString(f, content)
		return err
	}
	if err := add("[Content_Types].xml", contentTypesXML); err != nil {
		return err
	}
	if err := add("_rels/.rels", relsXML); err != nil {
		return err
	}
	if err := add("xl/workbook.xml", workbookXML); err != nil {
		return err
	}
	if err := add("xl/_rels/workbook.xml.rels", workbookRelsXML); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>`)
	rowN := 1
	emit := func(cells []string) {
		fmt.Fprintf(&sb, `<row r="%d">`, rowN)
		for c, val := range cells {
			ref := colName(c) + fmt.Sprintf("%d", rowN)
			fmt.Fprintf(&sb, `<c r="%s" t="inlineStr"><is><t xml:space="preserve">%s</t></is></c>`, ref, xmlEsc(deFormula(val)))
		}
		sb.WriteString(`</row>`)
		rowN++
	}
	emit([]string{"Flow Log Report"})
	for _, kv := range metaLines(m) {
		emit([]string{kv[0], kv[1]})
	}
	emit(nil)
	emit(reportCols)
	for _, r := range rows {
		emit(rowCells(r))
	}
	sb.WriteString(`</sheetData></worksheet>`)
	if err := add("xl/worksheets/sheet1.xml", sb.String()); err != nil {
		return err
	}
	return zw.Close()
}

func colName(i int) string {
	name := ""
	for i >= 0 {
		name = string(rune('A'+i%26)) + name
		i = i/26 - 1
	}
	return name
}

func xmlEsc(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return r.Replace(s)
}

const contentTypesXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
	`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
	`<Default Extension="xml" ContentType="application/xml"/>` +
	`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>` +
	`<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>` +
	`</Types>`

const relsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
	`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>` +
	`</Relationships>`

const workbookXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
	`<sheets><sheet name="FlowLogs" sheetId="1" r:id="rId1"/></sheets></workbook>`

const workbookRelsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
	`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>` +
	`</Relationships>`
