package director

import (
	"archive/zip"
	"encoding/csv"
	"fmt"
	"io"
	"strings"

	"github.com/go-pdf/fpdf"
)

// reportMeta is the lawful-query header printed on every exported report.
type reportMeta struct {
	CaseRef     string
	GeneratedBy string
	GeneratedAt string
	QueryIP     string
	QueryPort   int
	QueryProto  string
	From        string
	To          string
	Count       int
	Truncated   bool
}

// reportCols are the raw IPDR disclosure fields, in fixed order.
var reportCols = []string{"src_ip", "src_port", "dst_ip", "dst_port", "nat_ip", "nat_port", "timestamp", "proto"}

// reportHeads are the human-facing column titles (same order as reportCols).
var reportHeads = []string{"Source IP", "Src Port", "Destination IP", "Dst Port", "NAT IP", "NAT Port", "Timestamp (IST)", "Proto"}

func port(n int) string {
	if n <= 0 {
		return ""
	}
	return fmt.Sprintf("%d", n)
}

func rowCells(r natRecord) []string {
	return []string{
		r.PrivIP, port(r.PrivPort), r.DstIP, port(r.DstPort), r.PubIP, port(r.PubPort), r.Time, r.Proto,
	}
}

func metaLines(m reportMeta) [][2]string {
	port := "any"
	if m.QueryPort > 0 {
		port = fmt.Sprintf("%d", m.QueryPort)
	}
	proto := m.QueryProto
	if proto == "" || proto == "Any" {
		proto = "any"
	}
	recs := fmt.Sprintf("%d", m.Count)
	if m.Truncated {
		recs += " (truncated — narrow the time window or port)"
	}
	return [][2]string{
		{"Queried IP", orDash(m.QueryIP)}, {"Port", port}, {"Protocol", proto},
		{"Time window", m.From + " — " + m.To},
		{"Records", recs},
		{"Audit reason", orDash(m.CaseRef)},
		{"Generated", m.GeneratedAt},
		{"Generated by", m.GeneratedBy},
	}
}

func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "—"
	}
	return s
}

// deFormula neutralizes spreadsheet formula injection: a cell whose first char
// is = + - @ (or tab/CR) is executed as a formula by Excel/Sheets, so prefix it
// with a single quote. Applied to CSV/XLSX exports (not PDF).
func deFormula(s string) string {
	if s != "" && strings.ContainsRune("=+-@\t\r", rune(s[0])) {
		return "'" + s
	}
	return s
}

func safeCells(in []string) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = deFormula(v)
	}
	return out
}

// --- CSV ---

func writeCSV(w io.Writer, m reportMeta, rows []natRecord) error {
	cw := csv.NewWriter(w)
	_ = cw.Write([]string{"IP Detail Record (IPDR) Report"})
	for _, kv := range metaLines(m) {
		_ = cw.Write([]string{kv[0], deFormula(kv[1])})
	}
	_ = cw.Write(nil)
	_ = cw.Write(reportCols)
	for _, r := range rows {
		_ = cw.Write(safeCells(rowCells(r)))
	}
	cw.Flush()
	return cw.Error()
}

// --- PDF (landscape A4) ---

func writePDF(w io.Writer, m reportMeta, rows []natRecord) error {
	const lm = 8 // left margin
	widths := []float64{38, 20, 38, 20, 40, 20, 56, 22}
	tableW := 0.0
	for _, x := range widths {
		tableW += x
	}
	pdf := fpdf.New("L", "mm", "A4", "")
	pdf.SetMargins(lm, 10, lm)
	pdf.SetAutoPageBreak(true, 14)
	pdf.AliasNbPages("{nb}")
	tr := pdf.UnicodeTranslatorFromDescriptor("") // core fonts are CP1252 → translate UTF-8 (—, ·)

	drawColHeaders := func() {
		pdf.SetX(lm)
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(19, 102, 214)
		pdf.SetTextColor(255, 255, 255)
		for i, h := range reportHeads {
			al := "L"
			if i == 1 || i == 3 || i == 5 { // port columns right-aligned
				al = "R"
			}
			pdf.CellFormat(widths[i], 7, h, "", 0, al, true, 0, "")
		}
		pdf.Ln(-1)
	}
	drawMeta := func() {
		lines := metaLines(m)
		boxY := 21.0
		nrows := (len(lines) + 1) / 2
		boxH := float64(nrows)*5.4 + 4
		pdf.SetFillColor(246, 248, 251)
		pdf.SetDrawColor(221, 227, 234)
		pdf.Rect(lm, boxY, tableW, boxH, "FD")
		colW := tableW / 2
		for i, kv := range lines {
			col, row := i%2, i/2
			x := lm + 4 + float64(col)*colW
			y := boxY + 3 + float64(row)*5.4
			pdf.SetXY(x, y)
			pdf.SetFont("Helvetica", "", 8)
			pdf.SetTextColor(120, 128, 138)
			pdf.CellFormat(30, 4.8, kv[0], "", 0, "L", false, 0, "")
			pdf.SetFont("Helvetica", "B", 8)
			pdf.SetTextColor(27, 39, 51)
			pdf.CellFormat(colW-36, 4.8, tr(kv[1]), "", 0, "L", false, 0, "")
		}
		pdf.SetY(boxY + boxH + 3)
	}

	pdf.SetHeaderFunc(func() {
		// brand band (every page)
		pdf.SetFillColor(19, 102, 214)
		pdf.Rect(0, 0, 297, 17, "F")
		pdf.SetXY(lm+1, 3.5)
		pdf.SetFont("Helvetica", "B", 15)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(200, 9, "IP Detail Record (IPDR) Report", "", 0, "L", false, 0, "")
		pdf.SetXY(0, 6.2)
		pdf.SetFont("Helvetica", "", 8)
		pdf.CellFormat(289-lm, 5, tr("YesLogs Director — multi-ISP NAT / NetFlow IPDR"), "", 0, "R", false, 0, "")
		if pdf.PageNo() == 1 {
			drawMeta()
		} else {
			pdf.SetY(20)
		}
		drawColHeaders()
	})
	pdf.SetFooterFunc(func() {
		pdf.SetY(-11)
		pdf.SetFont("Helvetica", "I", 7)
		pdf.SetTextColor(150, 156, 164)
		pdf.CellFormat(0, 5, tr(fmt.Sprintf("Confidential — lawful-access disclosure · access is audited          Page %d of {nb}", pdf.PageNo())), "T", 0, "C", false, 0, "")
	})

	pdf.AddPage()
	pdf.SetFont("Courier", "", 7.5)
	pdf.SetTextColor(33, 41, 51)
	fill := false
	for _, r := range rows {
		pdf.SetX(lm)
		if fill {
			pdf.SetFillColor(245, 248, 251)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		for i, c := range rowCells(r) {
			al := "L"
			if i == 1 || i == 3 || i == 5 {
				al = "R"
			}
			pdf.CellFormat(widths[i], 5, trunc(c, 30), "LR", 0, al, true, 0, "")
		}
		pdf.Ln(-1)
		fill = !fill
	}
	if len(rows) == 0 {
		pdf.SetFont("Helvetica", "I", 9)
		pdf.SetTextColor(120, 128, 138)
		pdf.CellFormat(0, 10, "No records matched the query.", "", 1, "C", false, 0, "")
	}
	return pdf.Output(w)
}

func trunc(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}

// --- XLSX (hand-rolled minimal OOXML, inline strings, no deps) ---

func writeXLSX(w io.Writer, m reportMeta, rows []natRecord) error {
	zw := zip.NewWriter(w)
	add := func(name, content string) error {
		f, err := zw.Create(name)
		if err != nil {
			return err
		}
		_, err = io.WriteString(f, content)
		return err
	}
	if err := add("[Content_Types].xml", contentTypesXML); err != nil {
		return err
	}
	if err := add("_rels/.rels", relsXML); err != nil {
		return err
	}
	if err := add("xl/workbook.xml", workbookXML); err != nil {
		return err
	}
	if err := add("xl/_rels/workbook.xml.rels", workbookRelsXML); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>`)
	rowN := 1
	emit := func(cells []string) {
		fmt.Fprintf(&sb, `<row r="%d">`, rowN)
		for c, val := range cells {
			ref := colName(c) + fmt.Sprintf("%d", rowN)
			fmt.Fprintf(&sb, `<c r="%s" t="inlineStr"><is><t xml:space="preserve">%s</t></is></c>`, ref, xmlEsc(deFormula(val)))
		}
		sb.WriteString(`</row>`)
		rowN++
	}
	emit([]string{"IP Detail Record (IPDR) Report"})
	for _, kv := range metaLines(m) {
		emit([]string{kv[0], kv[1]})
	}
	emit(nil)
	emit(reportCols)
	for _, r := range rows {
		emit(rowCells(r))
	}
	sb.WriteString(`</sheetData></worksheet>`)
	if err := add("xl/worksheets/sheet1.xml", sb.String()); err != nil {
		return err
	}
	return zw.Close()
}

func colName(i int) string {
	name := ""
	for i >= 0 {
		name = string(rune('A'+i%26)) + name
		i = i/26 - 1
	}
	return name
}

func xmlEsc(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return r.Replace(s)
}

const contentTypesXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
	`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
	`<Default Extension="xml" ContentType="application/xml"/>` +
	`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>` +
	`<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>` +
	`</Types>`

const relsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
	`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>` +
	`</Relationships>`

const workbookXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
	`<sheets><sheet name="IPDR" sheetId="1" r:id="rId1"/></sheets></workbook>`

const workbookRelsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
	`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>` +
	`</Relationships>`
