package director

import (
	"archive/zip"
	"encoding/csv"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// reportMeta is the lawful-query header printed on every exported report.
type reportMeta struct {
	CaseRef     string
	GeneratedBy string
	GeneratedAt string
	QueryIP     string
	QueryPort   int
	QueryProto  string
	From        string
	To          string
	Count       int
	Truncated   bool
	NATOnly     bool
	MissingNAT  int
	CRM         crmEnrichmentSummary
}

// The exported evidence table has the operator-requested eight columns.
// CRM and audit context remain metadata; they never change the table shape.
var baseReportCols = []string{
	"Start Date(mm:dd:yyyy) & Time(hh:mm:ss)", "End Date(mm:dd:yyyy) & Time(hh:mm:ss)",
	"Source IP Address", "Source Port", "Translated IP address", "Translated Port", "Destination IP Address", "Destination Port",
}
var baseReportHeads = append([]string(nil), baseReportCols...)

func port(n int) string {
	if n < 0 {
		return ""
	}
	return fmt.Sprintf("%d", n)
}

func reportColumns(_ reportMeta) (cols, heads []string) {
	return append([]string(nil), baseReportCols...), append([]string(nil), baseReportHeads...)
}

func reportTimestamp(at time.Time, value string) string {
	if at.IsZero() {
		at = parseTime(value)
	}
	if at.IsZero() {
		return ""
	}
	return at.In(istLoc).Format("01:02:2006 & 15:04:05")
}

func rowCells(_ reportMeta, r natRecord) []string {
	r.setNATTranslation()
	ipPort := func(ip string, n int) string {
		if ip == "" {
			return ""
		}
		return port(n)
	}
	return []string{
		reportTimestamp(r.At, firstNonEmpty(r.StartTime, r.Time)), reportTimestamp(r.EndAt, r.EndTime),
		r.PrivIP, ipPort(r.PrivIP, r.PrivPort), r.NatIP, ipPort(r.NatIP, r.NatPort), r.DstIP, ipPort(r.DstIP, r.DstPort),
	}
}

func metaLines(m reportMeta) [][2]string {
	port := "any"
	if m.QueryPort > 0 {
		port = fmt.Sprintf("%d", m.QueryPort)
	}
	proto := m.QueryProto
	if proto == "" || proto == "Any" {
		proto = "any"
	}
	recs := fmt.Sprintf("%d", m.Count)
	if m.Truncated {
		recs += " (truncated — narrow the time window or port)"
	}
	scope := "all matching flows"
	if m.NATOnly {
		scope = "records with post-NAT fields; unknown means incomplete tuple evidence"
	}
	lines := [][2]string{
		{"Queried IP", orDash(m.QueryIP)}, {"Port", port}, {"Protocol", proto},
		{"Time window", m.From + " — " + m.To},
		{"Records", recs},
		{"Record scope", scope},
		{"Missing translated tuple", fmt.Sprintf("%d rows; blank means source translation not established", m.MissingNAT)},
		{"Time fields", "Stored flow_start / flow_end in IST; no session duration inferred"},
		{"Audit reason", orDash(m.CaseRef)},
		{"Generated", m.GeneratedAt},
		{"Generated by", m.GeneratedBy},
	}
	if m.CRM.Enabled {
		crm := fmt.Sprintf("%d matched · %d not found · %d ambiguous · %d failed",
			m.CRM.Matched, m.CRM.NotFound, m.CRM.Ambiguous, m.CRM.Failed)
		lines = append(lines, [2]string{"CRM enrichment", crm})
	}
	return lines
}

func orDash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "—"
	}
	return s
}

// deFormula neutralizes spreadsheet formula injection: a cell whose first char
// is = + - @ (or tab/CR) is executed as a formula by Excel/Sheets, so prefix it
// with a single quote. Applied to CSV/XLSX exports (not PDF).
func deFormula(s string) string {
	if s != "" && strings.ContainsRune("=+-@\t\r", rune(s[0])) {
		return "'" + s
	}
	return s
}

func safeCells(in []string) []string {
	out := make([]string, len(in))
	for i, v := range in {
		out[i] = deFormula(v)
	}
	return out
}

// --- CSV ---

func writeCSV(w io.Writer, m reportMeta, rows []natRecord) error {
	cw := csv.NewWriter(w)
	cols, _ := reportColumns(m)
	if err := cw.Write(cols); err != nil {
		return err
	}
	for _, r := range rows {
		if err := cw.Write(safeCells(rowCells(m, r))); err != nil {
			return err
		}
	}
	cw.Flush()
	return cw.Error()
}

// --- PDF (landscape A4) ---

func writePDF(w io.Writer, m reportMeta, rows []natRecord) error {
	const lm = 8 // left margin
	widths := []float64{43, 43, 37, 14, 37, 14, 37, 14}
	paper, pageW, rowFont := "A4", 297.0, 7.5
	_, heads := reportColumns(m)
	tableW := 0.0
	for _, x := range widths {
		tableW += x
	}
	pdf := fpdf.New("L", "mm", paper, "")
	pdf.SetMargins(lm, 10, lm)
	pdf.SetAutoPageBreak(true, 14)
	pdf.AliasNbPages("{nb}")
	tr := pdf.UnicodeTranslatorFromDescriptor("") // core fonts are CP1252 → translate UTF-8 (—, ·)

	drawColHeaders := func() {
		pdf.SetX(lm)
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetFillColor(19, 102, 214)
		pdf.SetTextColor(255, 255, 255)
		y := pdf.GetY()
		x := float64(lm)
		for i, h := range heads {
			pdf.SetXY(x, y)
			pdf.Rect(x, y, widths[i], 18, "F")
			pdf.MultiCell(widths[i], 4.5, h, "", "L", false)
			x += widths[i]
		}
		pdf.SetXY(lm, y+18)

	}
	drawMeta := func() {
		lines := metaLines(m)
		boxY := 21.0
		nrows := (len(lines) + 1) / 2
		boxH := float64(nrows)*5.4 + 4
		pdf.SetFillColor(246, 248, 251)
		pdf.SetDrawColor(221, 227, 234)
		pdf.Rect(lm, boxY, tableW, boxH, "FD")
		colW := tableW / 2
		for i, kv := range lines {
			col, row := i%2, i/2
			x := lm + 4 + float64(col)*colW
			y := boxY + 3 + float64(row)*5.4
			pdf.SetXY(x, y)
			pdf.SetFont("Helvetica", "", 8)
			pdf.SetTextColor(120, 128, 138)
			pdf.CellFormat(30, 4.8, kv[0], "", 0, "L", false, 0, "")
			pdf.SetFont("Helvetica", "B", 8)
			pdf.SetTextColor(27, 39, 51)
			pdf.CellFormat(colW-36, 4.8, tr(kv[1]), "", 0, "L", false, 0, "")
		}
		pdf.SetY(boxY + boxH + 3)
	}

	pdf.SetHeaderFunc(func() {
		// brand band (every page)
		pdf.SetFillColor(19, 102, 214)
		pdf.Rect(0, 0, pageW, 17, "F")
		pdf.SetXY(lm+1, 3.5)
		pdf.SetFont("Helvetica", "B", 15)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(200, 9, "IP Detail Record (IPDR) Report", "", 0, "L", false, 0, "")
		pdf.SetXY(0, 6.2)
		pdf.SetFont("Helvetica", "", 8)
		pdf.CellFormat(pageW-lm*2, 5, tr("YesLogs Director — multi-ISP NAT / NetFlow IPDR"), "", 0, "R", false, 0, "")
		if pdf.PageNo() == 1 {
			drawMeta()
		} else {
			pdf.SetY(20)
		}
		drawColHeaders()
	})
	pdf.SetFooterFunc(func() {
		pdf.SetY(-11)
		pdf.SetFont("Helvetica", "I", 7)
		pdf.SetTextColor(150, 156, 164)
		pdf.CellFormat(0, 5, tr(fmt.Sprintf("Confidential — lawful-access disclosure · access is audited          Page %d of {nb}", pdf.PageNo())), "T", 0, "C", false, 0, "")
	})

	pdf.AddPage()
	pdf.SetFont("Courier", "", rowFont)
	pdf.SetTextColor(33, 41, 51)
	fill := false
	for _, r := range rows {
		pdf.SetX(lm)
		if fill {
			pdf.SetFillColor(245, 248, 251)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		for i, c := range rowCells(m, r) {
			al := "L"
			if i == 3 || i == 5 || i == 7 {
				al = "R"
			}
			maxChars := int(widths[i] / 1.3)
			if maxChars < 8 {
				maxChars = 8
			}
			pdf.CellFormat(widths[i], 5, tr(trunc(c, maxChars)), "LR", 0, al, true, 0, "")
		}
		pdf.Ln(-1)
		fill = !fill
	}
	if len(rows) == 0 {
		pdf.SetFont("Helvetica", "I", 9)
		pdf.SetTextColor(120, 128, 138)
		pdf.CellFormat(0, 10, "No records matched the query.", "", 1, "C", false, 0, "")
	}
	return pdf.Output(w)
}

func trunc(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n-1]) + "…"
}

// --- XLSX (hand-rolled minimal OOXML, inline strings, no deps) ---

func writeXLSX(w io.Writer, m reportMeta, rows []natRecord) error {
	zw := zip.NewWriter(w)
	add := func(name, content string) error {
		f, err := zw.Create(name)
		if err != nil {
			return err
		}
		_, err = io.WriteString(f, content)
		return err
	}
	if err := add("[Content_Types].xml", contentTypesXML); err != nil {
		return err
	}
	if err := add("_rels/.rels", relsXML); err != nil {
		return err
	}
	if err := add("xl/workbook.xml", workbookXML); err != nil {
		return err
	}
	if err := add("xl/_rels/workbook.xml.rels", workbookRelsXML); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`)
	sb.WriteString(`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>`)
	rowN := 1
	emit := func(cells []string) {
		fmt.Fprintf(&sb, `<row r="%d">`, rowN)
		for c, val := range cells {
			ref := colName(c) + fmt.Sprintf("%d", rowN)
			fmt.Fprintf(&sb, `<c r="%s" t="inlineStr"><is><t xml:space="preserve">%s</t></is></c>`, ref, xmlEsc(deFormula(val)))
		}
		sb.WriteString(`</row>`)
		rowN++
	}
	emit([]string{"IP Detail Record (IPDR) Report"})
	for _, kv := range metaLines(m) {
		emit([]string{kv[0], kv[1]})
	}
	emit(nil)
	cols, _ := reportColumns(m)
	emit(cols)
	for _, r := range rows {
		emit(rowCells(m, r))
	}
	sb.WriteString(`</sheetData></worksheet>`)
	if err := add("xl/worksheets/sheet1.xml", sb.String()); err != nil {
		return err
	}
	return zw.Close()
}

func colName(i int) string {
	name := ""
	for i >= 0 {
		name = string(rune('A'+i%26)) + name
		i = i/26 - 1
	}
	return name
}

func xmlEsc(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return r.Replace(s)
}

const contentTypesXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">` +
	`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>` +
	`<Default Extension="xml" ContentType="application/xml"/>` +
	`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>` +
	`<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>` +
	`</Types>`

const relsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
	`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>` +
	`</Relationships>`

const workbookXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">` +
	`<sheets><sheet name="IPDR" sheetId="1" r:id="rId1"/></sheets></workbook>`

const workbookRelsXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` +
	`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">` +
	`<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>` +
	`</Relationships>`
