// Combined remaining-module browser contract. All API responses are isolated fixtures.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('../tests/e2e/node_modules/@playwright/test');
const root=path.resolve(process.argv[2]||'internal/director/web/console'),mime={'.js':'application/javascript','.css':'text/css','.html':'text/html','.woff2':'font/woff2'};
(async()=>{const browser=await chromium.launch({args:['--no-sandbox']});try{for(const director of [true,false]){
 const page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(12000);const errors=[],writes=[];let failRead='',failWrite=0,delayAudit=0;
 const isps=[{ID:1,Name:'Alpha ISP'},{ID:2,Name:'Beta ISP'}],users=[{id:1,email:'admin@example.invalid',role:'director',ispId:0,self:director,primary:false,version:'v1',createdAt:'2026-09-08 10:00'},{id:2,email:'primary@alpha.example',role:'isp',ispId:1,self:!director,primary:true,version:'v1',createdAt:'2026-09-08 10:00'},{id:3,email:'operator@alpha.example',role:'isp',ispId:1,self:false,primary:false,version:'v1',createdAt:'2026-09-08 10:00'}];let next=10;
 const settings={dataplane:{batchSize:5000,flushIntervalMs:300,writerWorkers:2,maxQueueRows:200000,backpressureMode:'block',unknownExporterMode:'reject'},skiprules:{skipDns:false,skipPrivate:false,skipZero:false},retention:{days:180},s3:{enabled:true,endpoint:'https://s3.example.invalid',region:'us-east-1',bucket:'archive',accessKey:'fixture-key',secretKey:'••••••••',pathPrefix:'natlog',exportFormat:'parquet',autoArchive:true,archiveAfterDays:7},notifications:{enabled:false,smtpHost:'smtp.example.invalid',smtpPort:587,smtpTls:'starttls',smtpUser:'alerts@example.invalid',smtpPassword:'••••••••',fromAddr:'alerts@example.invalid',recipients:'noc@example.invalid',silenceMins:15,remindHours:0},crmConnectors:[{ispId:1,enabled:true,endpoint:'https://crm.example.invalid/lookups',apiKey:'••••••••',timeoutMs:5000,batchSize:500}]};
 const queries=Array.from({length:31},(_,i)=>({ID:i+1,ISPID:1,UserEmail:'operator@alpha.example',QueryIP:'100.64.1.10',QueryPort:4321,QueryProto:'UDP',FromTS:'2026-09-01T08:00:00+05:30',ToTS:'2026-09-01T09:00:00+05:30',ResultCount:i+1,CaseRef:i%2?'Case 123 [export:csv]':'Incident inquiry',CreatedAt:'2026-09-08T11:00:00+05:30'}));
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('http://pages.test/**',async r=>{const u=new URL(r.request().url()),p=u.pathname,method=r.request().method(),reply=(status,data)=>r.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
  if(!p.startsWith('/api/')){const relative=p==='/'?'index.html':p.replace(/^\/_ui\/[a-f0-9]{40}\//,'/').slice(1),file=path.resolve(root,relative);if(!file.startsWith(root+path.sep)||!fs.existsSync(file))return r.fulfill({status:404});return r.fulfill({contentType:mime[path.extname(file)]||'application/octet-stream',body:fs.readFileSync(file)})}
  if(p==='/api/v1/me')return reply(200,{email:director?'admin@example.invalid':'primary@alpha.example',isDirector:director,ispId:director?0:1,role:director?'director':'isp',csrf:'test-csrf'});
  if(method==='GET'&&p===failRead)return reply(503,{error:'Fixture temporarily unavailable'});
  if(method!=='GET'){const body=r.request().postDataJSON();writes.push({p,method,body,csrf:r.request().headers()['x-csrf-token'],version:r.request().headers()['x-settings-version']});if(failWrite)return reply(failWrite,{error:'Save rejected',fields:failWrite===422?{Email:'Server email validation'}:{}})}
  if(p==='/api/v1/devices')return reply(200,{devices:[{ID:1,ISPID:1,DeviceID:1,Name:'Alpha edge',ExporterIP:'192.0.2.1',Enabled:true}],...(director?{isps}:{}),health:{1:{status:'online'}}});
  if(p.startsWith('/api/v1/users')){const id=+p.split('/')[4],user=users.find(x=>x.id===id);if(method==='GET')return reply(200,id?user:{users:users.filter(u=>director||u.ispId===1),...(director?{isps}:{}),editableUsers:true});const b=r.request().postDataJSON();if(method==='POST'&&!id){users.push({id:next++,email:b.Email,role:b.Role,ispId:b.ISPID,self:false,primary:false,createdAt:'2026-09-08 12:00',version:'v1'});return reply(200,{ok:true})}if(user&&b.Version!==user.version)return reply(409,{error:'Account changed; reopen it.'});if(method==='PUT')Object.assign(user,{email:b.Email,version:'v2'});if(method==='DELETE')users.splice(users.indexOf(user),1);return reply(200,{ok:true})}
  if(p==='/api/v1/account/password')return reply(200,{ok:true});
  if(p==='/api/v1/settings')return reply(200,{settings,isps,secretSet:true,notifyPassSet:true,crmKeySet:{1:true},versions:{dataplane:"v1",skiprules:"v1",retention:"v1",s3:"v1",notifications:"v1","crm:1":"v1","crm:new":"v1"}});
  if(p.startsWith('/api/v1/settings/')){const k=p.split('/').at(-1),b=r.request().postDataJSON();if(k==='crm'){const at=settings.crmConnectors.findIndex(x=>x.ispId===b.ispId),v={...b,apiKey:b.apiKey||'••••••••'};if(at<0)settings.crmConnectors.push(v);else settings.crmConnectors[at]=v}else settings[k]={...settings[k],...b,...(k==='s3'?{secretKey:b.secretKey||'••••••••'}:{})};return reply(200,{ok:true})}
  if(p==='/api/v1/audit'){if(delayAudit)await new Promise(resolve=>setTimeout(resolve,delayAudit));return reply(200,{queries})}
  if(p==='/api/v1/search')return reply(200,{total:0,records:[],elapsedMs:12,cold:false,crm:{enabled:false}});
  if(p==='/api/v1/compliance')return reply(200,{available:true,windowMins:15,retentionDays:180,answerable:1,failing:1,missingDays:['2026-09-02'],unanswerableDays:[],devices:[{storeId:1,deviceId:1,name:'Alpha edge',exporterIp:'192.0.2.1',answerable:true,state:'answerable',flows:500,translated:480,withPort:480,lastFlow:'2026-09-08T08:00:00Z',detail:'Translated mappings present.',remedy:'No action required.'},{storeId:2,deviceId:2,name:'Silent edge',answerable:false,state:'silent',flows:0,translated:0,withPort:0,detail:'No recent flows.',remedy:'Check exporter configuration.'}],days:[{date:'2026-09-01',flows:500,translatedKnown:false,translated:0}]});
  if(p==='/api/v1/retention')return reply(200,{available:true,retentionDays:180,storage:{rows:10000,bytes:8192,human:'8 KiB'},window:{from:'2026-09-01',to:'2026-09-07'},perDay:[{date:'2026-09-07',count:10000}],archive:{enabled:true,canRun:director,auto:true,bucket:'archive',format:'parquet',archivedDays:director?[{Day:'2026-09-01',Objects:2,Rows:8000,Bytes:4096,ArchivedAt:'2026-09-08T08:00:00Z'}]:[]}});
  if(p.startsWith('/api/v1/archive/'))return reply(200,{ok:true});
  if(p==='/api/v1/dataplanes')return reply(200,{dataplanes:[{name:'local',kind:'embedded',status:'live',uptime:3600,ingested:50000,inserted:49000,skipped:900,queuePct:2},{name:'registered-agent',kind:'agent',status:'unknown'}]});
  if(p==='/api/v1/system')return reply(200,{cpu:{load1:0.5,cores:4},memory:{human:'1 GiB',totalHuman:'4 GiB'},disk:{human:'5 GiB',totalHuman:'50 GiB'},process:{heapHuman:'128 MiB',goroutines:100}});
  return reply(200,{});
 });
 const nav=async name=>{await page.locator(`#menu a[href="#/${name.toLowerCase()}"]`).click();await page.waitForFunction(()=>document.querySelector('.index-stats .l')?.textContent!=='Loading…'&&document.querySelector('.index-stats .l'));assert.equal(await page.locator('.index-stats .tile').count(),5)};
 const dialog=()=>page.getByRole('dialog'),submit=()=>dialog().locator('[type=submit]').click(),closed=()=>dialog().waitFor({state:'hidden'}),close=()=>page.keyboard.press('Escape');
 await page.goto('http://pages.test/#/users');await page.locator('[data-action=create]').waitFor();await page.waitForFunction(()=>document.querySelector('.index-stats .v')?.textContent==='3'||document.querySelector('.index-stats .v')?.textContent==='2');
 await page.locator('[data-action=create]').click();const before=writes.length;await submit();assert.equal(writes.length,before);assert(await dialog().locator('[aria-invalid=true]').count()>=3);
 const labels=await dialog().locator('.isp-field').evaluateAll(ns=>ns.map(n=>{const l=n.querySelector('label'),s=l?.querySelector('.req'),v=n.querySelector('input,select');return{icon:!!l?.querySelector('.ms'),prompt:v?.placeholder||v?.querySelector('option[value=""]')?.textContent,right:!s||!s.offsetParent||Math.abs(s.getBoundingClientRect().right-l.getBoundingClientRect().right)<2}}));assert(labels.every(f=>f.icon&&f.prompt&&f.right));
 await dialog().locator('[name=Email]').fill('new@alpha.example');if(director){await dialog().locator('[name=Role]').selectOption('isp');await dialog().locator('[name=ISPID]').selectOption('1')}await dialog().locator('[name=Password]').fill('New-password-123');await dialog().locator('[name=ConfirmPassword]').fill('New-password-123');
 failWrite=422;await submit();await page.getByText('Server email validation',{exact:true}).waitFor();assert.equal(await dialog().locator('[name=Email]').inputValue(),'new@alpha.example');failWrite=0;await submit();await closed();await page.getByText('new@alpha.example',{exact:true}).waitFor();assert.equal(writes.at(-1).body.ISPID,1);
 await page.locator('[data-action=edit][data-id="10"]').click();assert.equal(await dialog().locator('[name=Role]').isDisabled(),true);await dialog().locator('[name=Email]').fill('changed@alpha.example');await submit();await closed();await page.getByText('changed@alpha.example',{exact:true}).waitFor();assert.equal(writes.at(-1).body.Password,'');
 await page.locator('[data-action=edit][data-id="10"]').click();users.find(u=>u.id===10).version='v3';await submit();await page.getByText('Account changed; reopen it.').waitFor();await close();
 await page.locator('[data-action=own]').click();await dialog().locator('[name=OldPassword]').fill('Old-password-123');await dialog().locator('[name=NewPassword]').fill('Own-password-123');await dialog().locator('[name=ConfirmPassword]').fill('Own-password-123');await submit();await closed();assert.equal(writes.at(-1).p,'/api/v1/account/password');
 await page.locator('[data-action=delete][data-id="10"]').click();let n=writes.length;await submit();assert.equal(writes.length,n);await dialog().locator('[name=Email]').fill('changed@alpha.example');await submit();await closed();assert(!users.some(u=>u.id===10));assert.equal(await page.locator('[data-action=delete][data-id="2"]').count(),0);
 await nav('Audit');assert.equal(await page.locator('.module-table tbody tr').count(),25);await page.locator('[data-page="1"]').click();assert.equal(await page.locator('.module-table tbody tr').count(),6);await page.locator('[name=kind]').selectOption('export');assert.equal(await page.locator('.module-table tbody tr').count(),15);await page.locator('[data-action=details]').first().click();await dialog().getByText('UDP',{exact:true}).waitFor();await close();
 await nav('Reports');assert.equal(await page.locator('a[href^="/api/v1/report"]').count(),0);await page.locator('[data-action=new]').first().click();await page.locator('#s-msg').getByText(/Historical IP metadata/).waitFor();assert.equal(await page.locator('#s-pub').inputValue(),'');assert.equal(await page.locator('#s-proto').inputValue(),'UDP');assert.equal(await page.locator('#s-from').inputValue(),'2026-09-01 08:00');
 await page.locator('#s-clear').click();await page.locator('#s-pub').fill('999.1.2.3');n=writes.length;await page.locator('#s-run').click();assert.equal(writes.length,n);assert.equal(await page.locator('#s-pub').getAttribute('aria-invalid'),'true');await page.locator('#s-pub').fill('203.0.113.10');await page.locator('#s-port').fill('65536');await page.locator('#s-run').click();assert.equal(writes.length,n);await page.locator('#s-port').fill('443');await page.locator('#s-run').click();await page.locator('#logTable').waitFor();assert.equal(writes.at(-1).body.PublicIP,'203.0.113.10');assert.equal(await page.locator('.index-stats .v').first().innerText(),'0');assert.equal(await page.locator('#s-results a[href^="/api/v1/report"]').count(),3);
 await nav('Compliance');await page.locator('[name=state]').selectOption('attention');assert.equal(await page.locator('.module-table tbody tr').count(),1);await page.locator('[data-action=details]').click();await dialog().getByText('Check exporter configuration.',{exact:true}).waitFor();await close();assert(await page.getByText('Not measured',{exact:true}).isVisible());
 await nav('Retention');if(director){await page.locator('[data-action=day]').click();n=writes.length;await submit();assert.equal(writes.length,n);await dialog().locator('[name=confirmation]').fill('2026-09-07');await submit();await closed();assert.equal(writes.at(-1).p,'/api/v1/archive/2026-09-07');await page.locator('[data-action=sweep]').click();await dialog().getByText(/removes hot data/).waitFor();await close()}else{assert.equal(await page.locator('[data-action=day],[data-action=sweep]').count(),0);assert.equal(await page.locator('.index-stats .l').nth(2).innerText(),'Recorded traffic')}
 if(director){await nav('Dataplanes');assert.equal(await page.locator('.index-stats .v').nth(2).innerText(),'—');await page.locator('[data-action=details]').first().click();await dialog().getByText(/not per-second rates/).waitFor();await close();await nav('Settings');
  for(const k of ['dataplane','skiprules','retention','s3','notifications']){await page.locator(`[data-section=${k}]`).click();await dialog().waitFor();assert(await dialog().locator('.lbl .ms').count()>0);if(k==='dataplane'){await dialog().locator('[name=batchSize]').fill('2');n=writes.length;await submit();assert.equal(writes.length,n);await dialog().locator('[name=batchSize]').fill('6000');await submit();await closed();await page.locator('[data-section=dataplane]').click();assert.equal(await dialog().locator('[name=batchSize]').inputValue(),'6000');settings.dataplane.writerWorkers=3;await submit();await page.getByText(/section changed since you opened/).waitFor();await close()}else if(k==='s3'){assert.equal(await dialog().locator('[name=secretKey]').inputValue(),'');await submit();await closed();assert.equal(writes.at(-1).body.secretKey,'')}else await close()}
  await page.locator('[name=crmScope]').selectOption('1');await page.locator('[data-section=crm]').click();assert.equal(await dialog().locator('[name=apiKey]').inputValue(),'');await submit();await closed();assert.equal(writes.at(-1).body.ispId,1);await page.locator('[name=crmScope]').selectOption('2');await page.locator('[data-section=crm]').click();assert.equal(await dialog().locator('[name=endpoint]').inputValue(),'');assert.equal(await dialog().locator('[name=apiKey]').inputValue(),'');await close();
  n=writes.length;await page.locator('[data-test-email]').click();await dialog().getByText(/real email/).waitFor();await submit();assert.equal(writes.length,n);await close();
 }
 // All routes survive refresh; stale loads cannot overwrite the next page.
 for(const name of director?['Users','Logs','Reports','Audit','Retention','Compliance','Dataplanes','Settings']:['Users','Logs','Reports','Audit','Retention','Compliance']){await nav(name);await page.reload();await page.waitForFunction(()=>document.querySelector('.index-stats .l')?.textContent!=='Loading…'&&document.querySelector('.index-stats .l'));if(name==='Logs')await page.locator('#logs-form').waitFor();assert.equal(await page.locator('#pageTitle').innerText(),name);await page.evaluate(()=>document.fonts.ready);const badIcons=await page.locator('.module-page .ms').evaluateAll(nodes=>nodes.filter(n=>{if(n.querySelector('svg'))return false;const s=getComputedStyle(n),c=document.createElement('canvas').getContext('2d');c.font=s.fontWeight+' '+s.fontSize+' '+s.fontFamily;return c.measureText(n.textContent.trim()).width>parseFloat(s.fontSize)*1.6}).map(n=>n.textContent));assert.deepEqual(badIcons,[],name+' must use available icon glyphs: '+JSON.stringify(badIcons));assert.equal(await page.locator('.index-stats .tile').count(),5);assert.equal(await page.locator('.index-stats .tile').evaluateAll(ns=>new Set(ns.map(n=>n.offsetTop)).size),1);if(process.env.PAGES_SHOTS_DIR){fs.mkdirSync(process.env.PAGES_SHOTS_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.PAGES_SHOTS_DIR,`${director?'director':'isp'}-${name.toLowerCase()}.png`)})}}
 delayAudit=250;await page.locator('#menu a[href="#/audit"]').click();await page.locator('#menu a[href="#/users"]').click();await page.waitForTimeout(350);assert.equal(await page.locator('#pageTitle').innerText(),'Users');assert(await page.locator('[data-action=create]').isVisible());delayAudit=0;
 failRead='/api/v1/users';await page.locator('.module-refresh').click();await page.getByText('Fixture temporarily unavailable',{exact:true}).waitFor();failRead='';await page.locator('.module-refresh').click();await page.locator('.module-banner').waitFor({state:'hidden'});
 await page.locator('[data-action=create]').click();await page.setViewportSize({width:390,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert(await dialog().locator('.isp-modal-foot').evaluate(n=>n.getBoundingClientRect().bottom<=innerHeight));assert.equal(await dialog().locator('.btn').first().evaluate(n=>getComputedStyle(n).borderRadius),'0px');if(process.env.PAGES_SHOTS_DIR)await page.screenshot({path:path.join(process.env.PAGES_SHOTS_DIR,`${director?'director':'isp'}-mobile.png`)});await close();
 assert(writes.every(w=>w.csrf==='test-csrf'));assert(writes.filter(w=>w.p.startsWith('/api/v1/settings/')).every(w=>w.version==='v1')); assert.deepEqual(errors,[]);await page.unrouteAll({behavior:'ignoreErrors'});await page.close();
 }console.log('Combined console checks passed: all eight modules, both roles, modal user CRUD, runtime settings, archive confirmations, search validation, honest history, CSRF, route refresh, stale requests and mobile.');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
